### ISSUE TITLE
Migrate to github action for coveralls

### ISSUE THREAD

**Issue by patmmccann** [prebid/Prebid.js#13235]
We should remove the coveralls dependency, remove testing coverage in the gulpfile, remove the reviewer coverage utility, and just migrate everything into github actions. Here is an example yml from another project that uploads to coveralls. We'd also want to show coverage of the files touched in the pr.

```
name: Upload coverage to Coveralls

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npx gulp test-coverage
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./build/coverage/lcov.info
          parallel: false
          flag-name: run-${{ github.run_id }}
```
